# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcPricer.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='GrpcPricer.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10GrpcPricer.proto\"\x14\n\x04Line\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x01\"P\n\x0cPricingInput\x12\x13\n\x04past\x18\x01 \x03(\x0b\x32\x05.Line\x12\x1d\n\x15monitoringDateReached\x18\x02 \x01(\x08\x12\x0c\n\x04time\x18\x03 \x01(\x01\"Y\n\rPricingOutput\x12\r\n\x05price\x18\x01 \x01(\x01\x12\x0e\n\x06\x64\x65ltas\x18\x02 \x03(\x01\x12\x13\n\x0bpriceStdDev\x18\x03 \x01(\x01\x12\x14\n\x0c\x64\x65ltasStdDev\x18\x04 \x03(\x01\x32=\n\nGrpcPricer\x12/\n\x0ePriceAndDeltas\x12\r.PricingInput\x1a\x0e.PricingOutputb\x06proto3'
)




_LINE = _descriptor.Descriptor(
  name='Line',
  full_name='Line',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='Line.data', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=40,
)


_PRICINGINPUT = _descriptor.Descriptor(
  name='PricingInput',
  full_name='PricingInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='past', full_name='PricingInput.past', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='monitoringDateReached', full_name='PricingInput.monitoringDateReached', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time', full_name='PricingInput.time', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=122,
)


_PRICINGOUTPUT = _descriptor.Descriptor(
  name='PricingOutput',
  full_name='PricingOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='price', full_name='PricingOutput.price', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='deltas', full_name='PricingOutput.deltas', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='priceStdDev', full_name='PricingOutput.priceStdDev', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='deltasStdDev', full_name='PricingOutput.deltasStdDev', index=3,
      number=4, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=213,
)

_PRICINGINPUT.fields_by_name['past'].message_type = _LINE
DESCRIPTOR.message_types_by_name['Line'] = _LINE
DESCRIPTOR.message_types_by_name['PricingInput'] = _PRICINGINPUT
DESCRIPTOR.message_types_by_name['PricingOutput'] = _PRICINGOUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Line = _reflection.GeneratedProtocolMessageType('Line', (_message.Message,), {
  'DESCRIPTOR' : _LINE,
  '__module__' : 'GrpcPricer_pb2'
  # @@protoc_insertion_point(class_scope:Line)
  })
_sym_db.RegisterMessage(Line)

PricingInput = _reflection.GeneratedProtocolMessageType('PricingInput', (_message.Message,), {
  'DESCRIPTOR' : _PRICINGINPUT,
  '__module__' : 'GrpcPricer_pb2'
  # @@protoc_insertion_point(class_scope:PricingInput)
  })
_sym_db.RegisterMessage(PricingInput)

PricingOutput = _reflection.GeneratedProtocolMessageType('PricingOutput', (_message.Message,), {
  'DESCRIPTOR' : _PRICINGOUTPUT,
  '__module__' : 'GrpcPricer_pb2'
  # @@protoc_insertion_point(class_scope:PricingOutput)
  })
_sym_db.RegisterMessage(PricingOutput)



_GRPCPRICER = _descriptor.ServiceDescriptor(
  name='GrpcPricer',
  full_name='GrpcPricer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=215,
  serialized_end=276,
  methods=[
  _descriptor.MethodDescriptor(
    name='PriceAndDeltas',
    full_name='GrpcPricer.PriceAndDeltas',
    index=0,
    containing_service=None,
    input_type=_PRICINGINPUT,
    output_type=_PRICINGOUTPUT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GRPCPRICER)

DESCRIPTOR.services_by_name['GrpcPricer'] = _GRPCPRICER

# @@protoc_insertion_point(module_scope)
