addi            PASSED
add             PASSED
andi            PASSED
and             PASSED
auipc           PASSED
beq             PASSED
bge             PASSED
bgeu            PASSED
blt             PASSED
bltu            PASSED
bne             PASSED
csrrci_mepc     PASSED
csrrci_mie      PASSED
csrrci_mip      FAILED
csrrci_mstatus  PASSED
csrrci_mtvec    PASSED
csrrc_mepc      PASSED
csrrc_mie       PASSED
csrrc_mip       FAILED
csrrc_mstatus   PASSED
csrrc_mtvec     PASSED
csrrsi_mepc     PASSED
csrrsi_mie      PASSED
csrrsi_mip      FAILED
csrrsi_mstatus  PASSED
csrrsi_mtvec    PASSED
csrrs_mepc      PASSED
csrrs_mie       PASSED
csrrs_mip       FAILED
csrrs_mstatus   PASSED
csrrs_mtvec     PASSED
csrrwi_mepc     PASSED
csrrwi_mie      PASSED
csrrwi_mip      FAILED
csrrwi_mtvec    PASSED
csrrw_mepc      PASSED
csrrw_mie       PASSED
csrrw_mip       FAILED
csrrw_mstatus   PASSED
csrrw_mtvec     PASSED
jalr            PASSED
jal             PASSED
lb              PASSED
lbu             PASSED
lh              PASSED
lhu             PASSED
lui             PASSED
lw              PASSED
ori             PASSED
or              PASSED
rebouclage      PASSED
sb              PASSED
sh              PASSED
slli            PASSED
sll             PASSED
slti            PASSED
slt             PASSED
sltui           PASSED
sltu            PASSED
srai            PASSED
sra             PASSED
srli            PASSED
srl             PASSED
sub             PASSED
sw              PASSED
xori            PASSED
xor             PASSED
